export const employees = [
  {
    id: 1,
    name: "Aino Virtanen",
    title: "HR Manager",
    salary: 4200,
    phone: "040-1234567",
    email: "aino.virtanen@example.com",
    animal: "Owl",
    startDate: "2018-04-01",
    location: "Helsinki",
    department: "Human Resources",
    skills: ["Recruiting", "Communication", "Employee Relations"],
  },
  {
    id: 2,
    name: "Jari Niemi",
    title: "Software Developer",
    salary: 4800,
    phone: "045-7654321",
    email: "jari.niemi@example.com",
    animal: "Wolf",
    startDate: "2020-09-15",
    location: "Espoo",
    department: "IT",
    skills: ["JavaScript", "React", "Node.js"],
  },
  {
    id: 3,
    name: "Laura Laakso",
    title: "Marketing Specialist",
    salary: 3900,
    phone: "050-9988776",
    email: "laura.laakso@example.com",
    animal: "Fox",
    startDate: "2019-02-10",
    location: "Tampere",
    department: "Marketing",
    skills: ["SEO", "Content Creation", "Social Media"],
  },
  {
    id: 4,
    name: "Mikko Koskinen",
    title: "Data Analyst",
    salary: 4600,
    phone: "041-4567890",
    email: "mikko.koskinen@example.com",
    animal: "Bear",
    startDate: "2021-01-20",
    location: "Helsinki",
    department: "Business Intelligence",
    skills: ["SQL", "Python", "Data Visualization"],
  },
  {
    id: 5,
    name: "Emilia Rantanen",
    title: "UX Designer",
    salary: 4400,
    phone: "040-3344556",
    email: "emilia.rantanen@example.com",
    animal: "Cat",
    startDate: "2017-11-05",
    location: "Turku",
    department: "Design",
    skills: ["Wireframing", "Prototyping", "User Research"],
  },
  {
    id: 6,
    name: "Antti Salmi",
    title: "DevOps Engineer",
    salary: 5000,
    phone: "046-9988771",
    email: "antti.salmi@example.com",
    animal: "Eagle",
    startDate: "2016-06-30",
    location: "Espoo",
    department: "IT",
    skills: ["CI/CD", "AWS", "Docker"],
  },
  {
    id: 7,
    name: "Kaisa Mäkinen",
    title: "Project Manager",
    salary: 4700,
    phone: "044-6677889",
    email: "kaisa.makinen@example.com",
    animal: "Dolphin",
    startDate: "2015-09-01",
    location: "Vantaa",
    department: "Project Management",
    skills: ["Scrum", "Agile", "Team Leadership"],
  },
  {
    id: 8,
    name: "Teemu Lehtonen",
    title: "IT Support Specialist",
    salary: 3500,
    phone: "043-5566778",
    email: "teemu.lehtonen@example.com",
    animal: "Dog",
    startDate: "2022-03-12",
    location: "Helsinki",
    department: "Support",
    skills: ["Troubleshooting", "Customer Service", "Hardware"],
  },
  {
    id: 9,
    name: "Sanna Korhonen",
    title: "Finance Analyst",
    salary: 4300,
    phone: "045-1239876",
    email: "sanna.korhonen@example.com",
    animal: "Rabbit",
    startDate: "2018-08-18",
    location: "Lahti",
    department: "Finance",
    skills: ["Budgeting", "Forecasting", "Excel"],
  },
  {
    id: 10,
    name: "Ville Tuominen",
    title: "Legal Advisor",
    salary: 5200,
    phone: "042-7788990",
    email: "ville.tuominen@example.com",
    animal: "Hawk",
    startDate: "2014-05-25",
    location: "Helsinki",
    department: "Legal",
    skills: ["Contract Law", "Risk Management", "Compliance"],
  },
];
